//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.User = new HashSet<User>();
            this.WorkLog = new HashSet<WorkLog>();
        }
    
        public long id_employee { get; set; }
        public long service_number { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public long id_position { get; set; }
        public long id_department { get; set; }
        public string qualification { get; set; }
        public long id_rate { get; set; }
        public long id_status_employee { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        public virtual Rate Rate { get; set; }
        public virtual StatusEmployee StatusEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLog> WorkLog { get; set; }
    }
}
