//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentUsageLog
    {
        public long id_equipment_usage_log { get; set; }
        public long id_production_stage { get; set; }
        public long id_equipment { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
