//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.EquipmentUsageLog = new HashSet<EquipmentUsageLog>();
        }
    
        public long id_equipment { get; set; }
        public long inventory_number { get; set; }
        public string model { get; set; }
        public long id_type_equipment { get; set; }
        public System.DateTime date_input { get; set; }
        public long id_status_equipment { get; set; }
        public long id_schedule { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        public virtual StatusEquipment StatusEquipment { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipmentUsageLog> EquipmentUsageLog { get; set; }
    }
}
