//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public long id_order_product { get; set; }
        public long id_order { get; set; }
        public long id_product { get; set; }
        public decimal quantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductionOrder ProductionOrder { get; set; }
    }
}
