//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public long id_purchase_order_detail { get; set; }
        public long id_purchase_order { get; set; }
        public long id_material { get; set; }
        public decimal quantity { get; set; }
        public decimal unit_price { get; set; }
        public string conditions { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
