//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReceipt
    {
        public long id_purchase_receipt { get; set; }
        public long id_purchase_order { get; set; }
        public long id_warehouse { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
