//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalance
    {
        public long id_stock_balance { get; set; }
        public long id_warehouse { get; set; }
        public long id_material { get; set; }
        public decimal quantity { get; set; }
    
        public virtual Material Material { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
