//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public long id_user_role { get; set; }
        public long id_user { get; set; }
        public long id_role { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
