//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace integrated_production_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkLog
    {
        public long id_work_log { get; set; }
        public long id_production_stage { get; set; }
        public long id_employee { get; set; }
        public decimal hours_worked { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ProductionStage ProductionStage { get; set; }
    }
}
